
export const FETCH_EV_DATA_REQUEST = 'FETCH_EV_DATA_REQUEST';
export const FETCH_EV_DATA_SUCCESS = 'FETCH_EV_DATA_SUCCESS';
export const FETCH_EV_DATA_FAILURE = 'FETCH_EV_DATA_FAILURE';

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const CLOSE_SIDEBAR = 'CLOSE_SIDEBAR';
export const TOGGLE_THEME = 'TOGGLE_THEME';
export const SET_THEME = 'SET_THEME';
